[build]
command = "yarn build"
publish = "build"

[build.environment]
NODE_VERSION = "17.4.0"
YARN_VERSION = "1.22.11"

# https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
from = "/js/script.js"
to = "https://plausible.io/js/plausible.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 202
