name: Publish

on:
  push:
    tags:
      - v*.*.* # only trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn package

      - name: Publish package
        run: |
          yarn publish package
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
